PLAT-11211 updated default java bdk version
SymphonyPlatformSolutions/generator-symphony pull request #129
Opened 2021-08-04 15:50 UTC by symphony-soufiane

### Ticket
[PLAT-11211](https://perzoinc.atlassian.net/browse/PLAT-11211)

### Description
Updated default java bdk version after releasing Java BDK 2.2.1

2021-08-04 16:11 UTC, symphony-elias approved these changes

2021-08-04 16:15 UTC, symphony-youri commented
Don't we need to change SPRING_VERSION_DEFAULT?

2021-08-04 16:16 UTC, symphony-youri requested changes
SPRING_VERSION_DEFAULT should probably be aligned with the one from the BDK

2021-08-05 08:34 UTC, symphony-youri approved these changes

2021-08-05 08:37 UTC, symphony-youri commented
It fails because of    > Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 6.6.1
 we just need to update the gradle wrapper

2021-08-06 15:51 UTC, symphony-soufiane commented on generators/bdk/java/templates/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-bin.zip
This upgrade was required when upgraded spring default version to 2.5.3

2021-08-06 16:12 UTC, symphony-elias approved these changes
LGTM

2021-08-09 05:49 UTC, symphony-youri commented on generators/python-bots/templates/python/bots/elements_form/requirements.txt
> +sym-api-client-python>=1.3.6
ohhh that was an old version, have you tried to generate it and checked the bot is running?

2021-08-09 05:49 UTC, symphony-youri approved these changes

2021-08-09 08:26 UTC, merged